# Generated by Django 2.2.3 on 2019-07-24 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 24, 18, 9, 37, 865394))),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('seasonStart', models.DateField(blank=True, default=datetime.datetime(2019, 7, 24, 18, 9, 37, 972318))),
                ('seasonEnd', models.DateField(blank=True, default=datetime.datetime(2019, 7, 24, 18, 9, 37, 972318))),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('goalScored', models.IntegerField(default=0)),
                ('goalConceded', models.IntegerField(default=0)),
                ('goalDiff', models.IntegerField(default=0)),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamStages', to='league.LeagueStage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 24, 18, 9, 37, 975315))),
                ('matchDate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 24, 18, 9, 37, 975315))),
                ('homeTeamGoal', models.IntegerField(default=0)),
                ('awayTeamGoal', models.IntegerField(default=0)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeams', to='league.Team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeams', to='league.Team')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.LeagueStage')),
            ],
        ),
    ]
